#ifndef CONFIG_CODE_H
#define CONFIG_CODE_H

// Auto-generated by call_dec_generator
// Configuration for N=64, GF=64
// Generated on: Dec 24 2025 11:43:31

// #define SPC_DISABLED
// #define REP_DISABLED

#include "codes/N64_GF64.hpp"

#endif // CONFIG_CODE_H
