#ifndef CONFIG_CODE_H
#define CONFIG_CODE_H

// Auto-generated by call_dec_generator
// Configuration for N=64, GF=64
// Generated on: Dec 24 2025 11:43:31

#include "codes/N256_GF64.hpp"

#endif // CONFIG_CODE_H
