#ifndef CONFIG_CODE_H
#define CONFIG_CODE_H

// Auto-generated by call_dec_generator
// Configuration for N=512, GF=64
// Generated on: Dec 22 2025 13:04:10

#include "codes/N512_GF64.hpp"

#endif // CONFIG_CODE_H
